### ISSUE TITLE
latest PR failed

### ISSUE THREAD

**Issue by austinscreations** [OXRS-IO/OXRS-IO-WEBSITE#52]
Making note that:
NPM failure to rebuild oxrs.io in PR #51 

https://github.com/OXRS-IO/OXRS-IO-WEBSITE/runs/7057593918?check_suite_focus=true

**Comment by MakerDockio** [comment]
Spoken with MitchellR who is going to look into updating the build environment to get around the current NPM build issue.

**Comment by austinscreations** [comment]
Thanks for doing that @mrinc - I've been trying to keep up on the side bar and top bar navigation and to keep it functional in a logical way.

Glad it can be working again as we'll be having another large push of updates somewhat soon.

**Comment by mrinc** [comment]
The sidebar does seem to be a bit of a pain to keep up with... We could maybe change the way its loaded to make it easier to manage.
So instead of managing the sidebar in the config.sidebar.js file (new file) - we move one to each of the main folders.
So like inside the docs folder, there is a sidebar file there 
This would allow for a bit easier to manage context wise me thinks.

Nav bar doesn't change too much (well shouldn't have to) compared to the sidebar

What do you think?

**Comment by mrinc** [comment]
In order to fix the build I had to do a bunch of stuff and during so noticed the nav bar some how stopped working.
But you will notice the search now works - which it didn't before (due to a breaking config change).... just no one noticed it lol 

So thus why the split of the config files.

But yea, it's not live since PR - but make sure you npm i once you pull it down since package changes
Ideally, clear all temp files and then npm i, and run the project.
